---
title: "HW3"
author: "Michael Miller"
date: "2022-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load Libraries

```{r}
library(bench)
library(devtools)

devtools::install_github("mikemiller442/fastHierarchicalReg")
devtools::install_github("kangjian2016/fastBayesReg")

library(fastHierarchicalReg)
library(fastBayesReg)
```

### Simulate Data 1

```{r}
n <- 10000
numBeta <- 100
betaSD <- 0.75
XSD <- 0.5
errorSD <- 2.0
e <- rnorm(n, mean = 0, sd = errorSD)
beta <- rnorm(numBeta, mean = 0, sd = betaSD*errorSD)
Z <- matrix(NA, nrow = n, ncol = numBeta)
for (i in 1:ncol(Z)) {
  Z[,i] <- rnorm(n, mean = 0, sd = XSD)
}

y <- Z %*% beta + e
output <- y - mean(y)
```

### Run Gibbs Sampler

```{r}
X <- Z
testX <- Z
resp <- output
testResp <- output

numEpochs <- 10000
numDiscard <- 2000
numChains <- 4
numCores <- 8
lambdaSqPrior <- 1.0
regVarPrior <- 1.0

res <- linRegGibbsProcessed(X = X,
                            testX = testX,
                            Y = output,
                            testY = output,
                            regVarPrior = regVarPrior,
                            lambdaSqPrior = lambdaSqPrior,
                            numEpochs = numEpochs,
                            numDiscard = numDiscard,
                            numChains = numChains,
                            numCores = numCores)
```

### Compare means between model output to true values

```{r}
# Comparing beta
paramBeta <- as.numeric(res$postMeanList$beta)
all.equal(beta,paramBeta)

# Comparing lambda
paramLambda <- sqrt(as.numeric(res$postMeanList$lambdaSq))
all.equal(betaSD,paramLambda)

# Comparing sigma
paramSigma <- sqrt(as.numeric(res$postMeanList$regVar))
all.equal(errorSD,paramSigma)
```

### Simulate Data 2

```{r}
n <- 10000
numBeta <- 5
betaSD <- 0.75
XSD <- 0.5
errorSD <- 2.0
e <- rnorm(n, mean = 0, sd = errorSD)
beta <- rnorm(numBeta, mean = 0, sd = betaSD*errorSD)
Z <- matrix(NA, nrow = n, ncol = numBeta)
for (i in 1:ncol(Z)) {
  Z[,i] <- rnorm(n, mean = 0, sd = XSD)
}

y <- Z %*% beta + e
output <- y - mean(y)
```

### Run Gibbs Sampler For Methods Packages

```{r}
X <- Z
testX <- Z
resp <- output
testResp <- output

numEpochs <- 40000
numDiscard <- 2000
numChains <- 4
lambdaSqPrior <- 1.0
regVarPrior <- 1.0

res <- linRegGibbsProcessed(X = X,
                            testX = testX,
                            Y = output,
                            testY = output,
                            regVarPrior = regVarPrior,
                            lambdaSqPrior = lambdaSqPrior,
                            numEpochs = numEpochs,
                            numDiscard = numDiscard,
                            numChains = numChains,
                            numCores = numCores)

numEpochs <- 10000
numDiscard <- 2000

resKJ <- fastBayesReg::fast_normal_lm(y = y,
                                      X = X,
                                      mcmc_sample = numEpochs,
                                      burnin = numDiscard)
```

### Compare means between model output and Stan

```{r}
# Comparing beta
kjBeta <- as.numeric(resKJ$post_mean$betacoef)
paramBeta <- as.numeric(res$postMeanList$beta)
all.equal(stanBeta,paramBeta)

# Comparing lambda
kjLambda <- as.numeric(resKJ$post_mean$tau2)
paramLambda <- sqrt(as.numeric(res$postMeanList$lambdaSq))
all.equal(stanLambda,paramLambda)

# Comparing sigma
kjSigma <- as.numeric(resKJ$post_mean$sigma2_eps)
paramSigma <- sqrt(as.numeric(res$postMeanList$regVar))
all.equal(stanSigma,paramSigma)
```

### Compare covariance between model output and Stan

```{r}
# Comparing beta
stanBetaCov <- as.numeric(cov(model1[,1:(ncol(X))]))
paramBetaCov <- as.numeric(cov(t(res$resMat[1:(ncol(X)),])))
all.equal(stanBetaCov,paramBetaCov)

# Comparing lambda
stanLambdaCov <- as.numeric(var(model1[,ncol(X)+2]))
paramLambdaCov <- as.numeric(var(sqrt(res$resMat[ncol(X)+2,])))
all.equal(stanLambdaCov,paramLambdaCov)

# Comparing sigma
stanSigmaCov <- as.numeric(var(model1[,ncol(X)+3]))
paramSigmaCov <- as.numeric(var(sqrt(res$resMat[ncol(X)+4,])))
all.equal(stanSigmaCov,paramSigmaCov)
```

### Rhat Convergence Diagnostic - Check Convergence to 1.0

```{r}
print(unlist(res$RhatList))
all.equal(as.numeric(unlist(res$RhatList)),rep(1.0,length(unlist(res$RhatList))))
```


### Benchmark High Dimensional Example

```{r}
n <- 5000
numBeta <- 500
betaSD <- 0.05
XSD <- 0.5
errorSD <- 2.0
e <- rnorm(n, mean = 0, sd = errorSD)
beta <- rnorm(numBeta, mean = 0, sd = betaSD*errorSD)
Z <- matrix(NA, nrow = n, ncol = numBeta)
for (i in 1:ncol(Z)) {
  Z[,i] <- rnorm(n, mean = 0, sd = XSD)
}

y <- Z %*% beta + e
output <- y - mean(y)

funMod <- function() {
  X <- Z
  testX <- Z
  resp <- output
  testResp <- output
  
  numEpochs <- 4000
  numDiscard <- 2000
  numChains <- 2
  lambdaSqPrior <- 1.0
  regVarPrior <- 1.0
  
  res <- linRegGibbsProcessed(X = X,
                              testX = testX,
                              Y = output,
                              testY = output,
                              regVarPrior = regVarPrior,
                              lambdaSqPrior = lambdaSqPrior,
                              numEpochs = numEpochs,
                              numDiscard = numDiscard,
                              numChains = numChains)
  paramIntercept <- as.numeric(res$postMeanList$intercept)
  return(paramIntercept)
}

funStan <- function() {
  options(mc.cores = parallel::detectCores())

  X <- Z
  testX <- Z
  stanData <- list(N = nrow(X),
                   Y = as.numeric(output),
                   K = ncol(X),
                   X = X)

  m1 <- stan(file = "./../m1.stan",
             data = stanData,
             warmup = 1000,
             iter = 2000,
             control = list(adapt_delta = 0.95),
             chains = 2,
             cores = 8)

  model1 <- data.matrix(m1)
  stanIntercept <- as.numeric(mean(model1[,1]))
  return(stanIntercept)
}

benchMarkRes <- bench::mark(funMod(),
                            funStan(),
                            iterations = 2,
                            check = FALSE)
benchMarkTable <- benchMarkRes[c("expression", "min", "median","mem_alloc","n_gc")]
knitr::kable(benchMarkTable)
```















